export const typography = {
  fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontSize: 13,
  h1: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 700,
    fontSize: '1.25rem',
    lineHeight: 1.25,
    letterSpacing: '-0.015em',
  },
  h2: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 700,
    fontSize: '1.125rem',
    lineHeight: 1.28,
    letterSpacing: '-0.01em',
  },
  h3: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 700,
    fontSize: '1rem',
    lineHeight: 1.3,
  },
  h4: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 600,
    fontSize: '0.9375rem',
    lineHeight: 1.35,
  },
  h5: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 600,
    fontSize: '0.875rem',
    lineHeight: 1.4,
  },
  h6: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 600,
    fontSize: '0.8125rem',
    lineHeight: 1.45,
  },
  subtitle1: {
    fontWeight: 600,
    fontSize: '0.875rem',
    lineHeight: 1.5,
    color: '#0f172a',
  },
  subtitle2: {
    fontWeight: 600,
    fontSize: '0.8125rem',
    lineHeight: 1.5,
    color: '#475569',
  },
  body1: {
    fontSize: '0.8125rem',
    lineHeight: 1.55,
    color: '#334155',
  },
  body2: {
    fontSize: '0.8125rem',
    lineHeight: 1.5,
    color: '#475569',
  },
  button: {
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '0.8125rem',
    letterSpacing: '0.01em',
  },
  caption: {
    fontSize: '0.6875rem',
    lineHeight: 1.5,
    color: '#64748b',
  },
  overline: {
    fontSize: '0.6875rem',
    fontWeight: 700,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
};
