export const typography = {
  fontFamily: '"Outfit", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  h1: {
    fontFamily: '"Outfit", sans-serif',
    fontWeight: 800,
    fontSize: '2.5rem',
    lineHeight: 1.2,
    letterSpacing: '-0.025em',
  },
  h2: {
    fontFamily: '"Outfit", sans-serif',
    fontWeight: 800,
    fontSize: '2rem',
    lineHeight: 1.25,
    letterSpacing: '-0.02em',
  },
  h3: {
    fontFamily: '"Outfit", sans-serif',
    fontWeight: 700,
    fontSize: '1.625rem',
    lineHeight: 1.3,
    letterSpacing: '-0.015em',
  },
  h4: {
    fontFamily: '"Outfit", sans-serif',
    fontWeight: 700,
    fontSize: '1.375rem',
    lineHeight: 1.35,
    letterSpacing: '-0.01em',
  },
  h5: {
    fontFamily: '"Outfit", sans-serif',
    fontWeight: 600,
    fontSize: '1.125rem',
    lineHeight: 1.4,
  },
  h6: {
    fontFamily: '"Outfit", sans-serif',
    fontWeight: 600,
    fontSize: '1rem',
    lineHeight: 1.45,
  },
  subtitle1: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 600,
    fontSize: '1rem',
    lineHeight: 1.5,
    color: '#0f172a',
  },
  subtitle2: {
    fontFamily: '"Inter", sans-serif',
    fontWeight: 600,
    fontSize: '0.875rem',
    lineHeight: 1.57,
    color: '#475569',
  },
  body1: {
    fontFamily: '"Inter", sans-serif',
    fontSize: '0.95rem',
    lineHeight: 1.6,
    color: '#334155',
  },
  body2: {
    fontFamily: '"Inter", sans-serif',
    fontSize: '0.875rem',
    lineHeight: 1.57,
    color: '#475569',
  },
  button: {
    fontFamily: '"Inter", sans-serif',
    textTransform: 'none',
    fontWeight: 600,
    letterSpacing: '0.01em',
  },
  caption: {
    fontFamily: '"Inter", sans-serif',
    fontSize: '0.75rem',
    lineHeight: 1.5,
    color: '#64748b',
  },
  overline: {
    fontFamily: '"Inter", sans-serif',
    fontSize: '0.75rem',
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
};
